# @File: docker-compose-redis.yaml
# @Editor: PyCharm
# @Author: Austin (From Chengdu.China) https://fairy.host
# @HomePage: https://github.com/AustinFairyland
# @OperatingSystem: Windows 11 Professional Workstation 23H2 Canary Channel
# @CreatedTime: 2024-01-16

version: "3"
services:
  redis:
    image: redis:latest
    container_name: redis-standalone-service
    network_mode: bridge
    ports:
      - "51007:6379"
    command: [ "redis-server", "--requirepass", "Redis.pwd:112#." ]
networks:
  bridge:
    driver: bridge
