#!/bin/bash
# @File: start-portainer-service
# @Editor: PyCharm
# @Author: Austin (From Chengdu.China) https://fairy.host
# @HomePage: https://github.com/AustinFairyland
# @OperatingSystem: Windows 11 Professional Workstation 23H2 Canary Channel
# @CreatedTime: 2024-01-02

docker run -d --name protainer-serivce \
  --network DockerCustomNet \
  --ip 173.1.11.7 \
  -e TZ=Asia/Shanghai \
  -p 51007:9000 \
  -p 51008:8000 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /home/austin/data/containers/volume/portainer-service/data:/data \
  --restart always \
  docker.io/portainer/portainer-ce:latest
