#!/bin/bash
# File: start-halo-service
# Editor: PyCharm
# Author: Austin (From Chengdu.China) https://fairy.host
# HomePage: https://github.com/AustinFairyland
# OS: Linux Ubuntu 22.04.4 Kernel 6.2.0-36-generic
# CreatedTime: 2024/1/13

docker run -d --name halo-service \
  --network DockerCustomNet \
  --ip 173.1.11.6 \
  -p 51006:8090 \
  -e TZ=Asia/Shanghai \
  -v /home/austin/data/containers/volume/halo-service/2.11/data:/root/.halo2 \
  halohub/halo:2.11 --spring.r2dbc.url=r2dbc:pool:mysql://173.1.11.1:3306/austin_halo \
  --spring.r2dbc.username=austin \
  --spring.r2dbc.password=Austin.pwd:112#. \
  --spring.sql.init.platform=mysql \
  --halo.external-url=http://blog.fairies.ltd/ \
  --server.port=8090
