#!/bin/bash
# File: start-minio-service
# Editor: PyCharm
# Author: Austin (From Chengdu.China) https://fairy.host
# HomePage: https://github.com/AustinFairyland
# OS: Linux Ubuntu 22.04.4 Kernel 6.2.0-36-generic
# CreatedTime: 2023/12/22

docker run -d --name minio-service \
  --network DockerCustomNet \
  --ip 173.1.11.3 \
  -e "MINIO_ROOT_USER=Austin" \
  -e "MINIO_ROOT_PASSWORD=Austin.pwd:112#." \
  -e TZ=Asia/Shanghai \
  -p 51004:51004 \
  -p 51005:51005 \
  -v /home/austin/data/containers/volume/minio-service/data:/data \
  -v /home/austin/data/containers/volume/minio-service/config:/root/.minio \
  --restart=always \
  minio/minio server /data --console-address ":51004" --address ":51005"
