# @File: docker-compose-wiki.yaml
# @Editor: PyCharm
# @author: Lionel Johnson
# @HomePage: https://github.com/AustinFairyland
# @OperatingSystem: Windows 11 Professional Workstation 23H2 Canary Channel
# @CreatedTime: 2024-01-21

version: "3"
networks:
  bridge:
    driver: bridge
    external: true
services:
  wiki:
    image: requarks/wiki:2
    container_name: wiki-service
    network_mode: bridge
    ports:
      - "2078:3000"
    environment:
      DB_TYPE: postgres
      DB_HOST: mapping.fairies.ltd
      DB_PORT: 51005
      DB_USER: austinservice
      DB_PASS: Austin.pwd:112#.
      DB_NAME: internal_container_wiki
    restart: unless-stopped
