#!/bin/bash
# File: start-redis-service
# Editor: PyCharm
# Author: Austin (From Chengdu.China) https://fairy.host
# HomePage: https://github.com/AustinFairyland
# OS: Linux Ubuntu 22.04.4 Kernel 6.2.0-36-generic
# CreatedTime: 2023/12/23

docker run -d --name redis-service \
  --network DockerCustomNet \
  --ip 173.1.10.3 \
  -e TZ=Asia/Shanghai \
  -p 51003:6379 \
  --restart always \
  redis:7.2.4 redis-server --requirepass "Redis.pwd:112#."
