# @File: docker-compose-ittools.yaml
# @Editor: PyCharm
# @Author: Austin (From Chengdu.China) https://fairy.host
# @HomePage: https://github.com/AustinFairyland
# @OperatingSystem: Windows 11 Professional Workstation 23H2 Canary Channel
# @CreatedTime: 2024-01-16

version: '3'
services:
  it-tools:
    image: 'corentinth/it-tools:latest'
    container_name: it-tools-service
    restart: unless-stopped
    ports:
      - '51003:80'
